p_rayno_cas_auth:
    server_login_url: https://auth.isen-ouest.fr/cas
    server_validation_url: https://auth.isen-ouest.fr/cas/serviceValidate
    server_logout_url: https://auth.isen-ouest.fr/cas/logout

    # xml_namespace: cas
    # options:[] see http://docs.guzzlephp.org/en/latest/request-options.html
